const SECRET_KEY = 'SECRETKEY'
const DUPLICATE_ENTRY = 'ER_DUP_ENTRY';
const BAD_REQUEST_CODE = 'ERR_BAD_REQUEST';
const FETCH_DATA_ERROR_MESSAGE = 'ERROR FECTH DATA';
const BAD_USER = 'USUARIO O CONTRASEÑA INCORRECTA';

module.exports = {
    SECRET_KEY,
    DUPLICATE_ENTRY,
    BAD_REQUEST_CODE,
    FETCH_DATA_ERROR_MESSAGE,
    BAD_USER
};